ground_truth:
  ros__parameters:
    longitude: -84.405001
    latitude: 33.774497
    x_noise_std_dev: 0.0
    y_noise_std_dev: 0.0
    z_noise_std_dev: 0.0
    roll_noise_std_dev: 0.0
    pitch_noise_std_dev: 0.0
    yaw_noise_std_dev: 0.0