controller_manager:
  ros__parameters:
    update_rate: 200

    imu_broadcaster:
      type: urc_controllers/IMUBroadcaster

    status_light_controller:
      type: urc_controllers/StatusLightController

    rover_drivetrain_controller:
      type: diff_drive_controller/DiffDriveController

    bms_broadcaster:
      type: urc_controllers/BMSBroadcaster

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: velocity_controllers/JointGroupVelocityController

    gripper_controller_left:
      type: position_controllers/GripperActionController

    gripper_controller_right:
      type: position_controllers/GripperActionController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

imu_broadcaster:
  ros__parameters:
    imu_name: imu_sensor

bms_broadcaster:
  ros__parameters:
    bms_name: battery_management
    cell_num: 6

status_light_controller:
  ros__parameters:
    status_light_name: status_light

rover_drivetrain_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel"]
    right_wheel_names: ["right_wheel"]

    pose_covariance_diagonal:
      [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal:
      [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    position_feedback: false
    open_loop: true

    wheel_seperation: 0.5

    wheel_radius: 0.20
    cmd_vel_timeout: 0.5
    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 4.0 # m/s
        min_velocity: -0.5 # m/s
        has_acceleration_limits: true
        max_acceleration: 0.8 # m/s^2
        min_acceleration: -0.4 # m/s^2
        has_jerk_limits: true
        max_jerk: 5.0 # m/s^3
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.7 # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.5 # rad/s^2
        has_jerk_limits: true
        max_jerk: 2.5 # rad/s^3

arm_controller:
  ros__parameters:
    joints:
      - shoulderjoint
      - bicepjoint
      - elbowjoint
      - wristjoint
      - clawjoint

gripper_controller_left:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    max_effort: 0.50
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001
    joint: leftgripperjoint

gripper_controller_right:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    max_effort: 0.50
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001
    joint: rightgripperjoint
