controller_manager:
  ros__parameters:
    update_rate: 200
    use_sim_time: true

    imu_broadcaster:
      type: urc_controllers/IMUBroadcaster

    status_light_controller:
      type: urc_controllers/StatusLightController

    rover_drivetrain_controller:
      type: diff_drive_controller/DiffDriveController

    bms_broadcaster:
      type: urc_controllers/BMSBroadcaster

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

imu_broadcaster:
  ros__parameters:
    imu_name: imu_sensor

bms_broadcaster:
  ros__parameters:
    bms_name: battery_management
    cell_num: 6

status_light_controller:
  ros__parameters:
    status_light_name: status_light

# For more information on each of these parameters, see https://github.com/ros-controls/ros2_controllers/blob/master/diff_drive_controller/src/diff_drive_controller_parameter.yaml
rover_drivetrain_controller:
  ros__parameters:
    left_wheel_names:
      [
        "left_front_wheel_joint",
        "left_center_wheel_joint",
        "left_rear_wheel_joint",
      ]
    right_wheel_names:
      [
        "right_front_wheel_joint",
        "right_center_wheel_joint",
        "right_rear_wheel_joint",
      ]

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    wheel_seperation: 0.08
    wheels_per_side: 3
    wheel_radius: 0.1

    use_stamped_vel: true

    enable_odom_tf: true

    cmd_vel_timeout: 0.5

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 5.0
    linear.x.min_velocity: -5.0
    linear.x.max_acceleration: -1.0
    linear.x.max_acceleration: 1.0

arm_controller:
  ros__parameters:
    joints:
      - shoulderjoint
      - bicepjoint
      - elbowjoint
      - wristjoint
      - clawjoint

gripper_controller_left:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    max_effort: 0.50
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001
    joint: leftgripperjoint

gripper_controller_right:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    max_effort: 0.50
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001
    joint: rightgripperjoint

joy_drive:
  ros__parameters:
    max_linear_velocity_ms: 3.0
    max_angular_velocity_radians: 5.0
    joy_command_topic: /driver/joy
    cmd_vel_topic: /rover_drivetrain_controller/cmd_vel
    target_axes: [1, 3]
    invert_linear_velocity: false
    invert_angular_velocity: false

