controller_manager:
  ros__parameters:
    update_rate: 200
    use_sim_time: true

    imu_broadcaster:
      type: urc_controllers/IMUBroadcaster

    status_light_controller:
      type: urc_controllers/StatusLightController

    rover_drivetrain_controller:
      type: diff_drive_controller/DiffDriveController

    bms_broadcaster:
      type: urc_controllers/BMSBroadcaster

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

imu_broadcaster:
  ros__parameters:
    imu_name: imu_sensor

bms_broadcaster:
  ros__parameters:
    bms_name: battery_management
    cell_num: 6

status_light_controller:
  ros__parameters:
    status_light_name: status_light

# For more information on each of these parameters, see https://github.com/ros-controls/ros2_controllers/blob/master/diff_drive_controller/src/diff_drive_controller_parameter.yaml
rover_drivetrain_controller:
  ros__parameters:
    left_wheel_names:
      [
        "left_front_wheel_joint",
        "left_center_wheel_joint",
        "left_rear_wheel_joint",
      ]
    right_wheel_names:
      [
        "right_front_wheel_joint",
        "right_center_wheel_joint",
        "right_rear_wheel_joint",
      ]

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    wheel_seperation: 0.45
    wheels_per_side: 3
    wheel_radius: 0.08

    use_stamped_vel: false

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0
