joystick_driver:
  ros__parameters:
    max_velocity: 4.0
    delta_velocity: 0.1

    driver_joystick_topic: "/joy"
    velocity_x_axis: 1
    velocity_z_axis: 4
    left_invert: True
    right_invert: True

    drivetrain_topic: "rover_drivetrain/cmd_vel"