joystick_driver:
  ros__parameters:
    max_velocity: 4.0
    delta_velocity: 0.1

    driver_joystick_topic: "/driver/joy"
    driver_velocity_x_axis: 1
    driver_velocity_z_axis: 4
    driver_left_invert: True
    driver_right_invert: True

    drivetrain_topic: "rover_drivetrain_controller/cmd_vel"