twist_mux:
  ros__parameters:
    topics:
      input1:
        name: autonomous_navigation
        topic: /cmd_vel_autonomous
        timeout: 0.0
        priority: 1
      input2:
        name: teleoperation
        topic: /cmd_vel_teleop
        timeout: 0.0
        priority: 3

    locks:
      e_stop:
        topic: /e_stop
        timeout: 0.0
        priority: 255

      teleoperation:
        topic: /teleop_enabled
        timeout: 0.0
        priority: 2
