controller_manager:
  ros__parameters:
    update_rate: 120

    imu_broadcaster:
      type: urc_controllers/IMUBroadcaster

    status_light_controller:
      type: urc_controllers/StatusLightController

imu_broadcaster:
  ros__parameters:
    imu_name: imu_sensor

status_light_controller:
  ros__parameters:
    status_light_name: status_light

    