elevation_mapping:
  ros__parameters:
    map_frame: "odom"
    camera_frame: "camera_depth_frame"
    resolution: 0.1
    width: 60
    depth_topic: "/depth_camera/points"
    min_z: 0.1
    max_z: 3.0
