controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulderjoint
      - bicepjoint
      - elbowjoint
      - forearmjoint
      - endeffectorjoint
      - clawbasejoint
  - name: fake_claw_controller
    type: $(arg fake_execution_type)
    joints:
      - leftgripperjoint
      - rightgripperjoint
initial:  # Define initial robot poses per group
#  - group: arm
#    pose: home

  []