<?xml version='1.0'?>

<robot name="wallii" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="walli_prop.xacro"/>
  <xacro:include filename="walli_inertials.xacro"/>

  <!-- The "wheel" macro defines an axle carrier, axle, and wheel. -->
  <xacro:macro name="wheel" params="lr_prefix fr_prefix lr_pos fr_pos">
    <joint name="${lr_prefix}_${fr_prefix}_axle" type="continuous">
      <parent link="base_link"/>
      <child link="${lr_prefix}_${fr_prefix}_wheel"/>
      <origin xyz="${fr_pos}
                   ${lr_pos}
                   ${- body_clearance}"
              rpy="${degrees_90} 0 0"/>
      <axis xyz="0 0 -1"/>
      <limit effort="${axle_eff_limit}" velocity="${axle_vel_limit}"/>
    </joint>
    <ros2_control name="GazeboSystem" type="system">
      <transmission name="${lr_prefix}_${fr_prefix}_axle_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${lr_prefix}_${fr_prefix}_axle">
          <hardwareInterface>VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="${lr_prefix}_${fr_prefix}_axle_act">
          <hardwareInterface>VelocityJointInterface</hardwareInterface>
          <mechanicalReduction>1</mechanicalReduction>
        </actuator>
      </transmission>
    </ros2_control>

    <link name="${lr_prefix}_${fr_prefix}_wheel">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="${tire_dia / 2}" length="${tire_width}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="${tire_dia / 2}" length="${tire_width}"/>
        </geometry>
      </collision>

      <xacro:thick_walled_tube_inertial
          inner_rad="${hub_dia / 2}" outer_rad="${tire_dia / 2}"
          height="${tire_width}" mass="${wheel_mass}"/>
    </link>

    <gazebo reference="${lr_prefix}_${fr_prefix}_wheel">
      <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>

  <!-- base_link must have geometry so that its axes can be displayed in
       rviz. -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.01"/>
      </geometry>
      <material name="body_mat"/>
    </visual>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/Green</material>
  </gazebo>

  <link name="imu">
    <visual>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </visual>
    
    <collision>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
      
    <xacro:box_inertia m="0.1" w="0.1" d="0.1" h="0.1"/>
  </link>

  <joint name="imu_joint" type="fixed">
		<axis xyz="1 0 0"/>
		<origin xyz="0 0 0.05"/>
		<parent link="base_link"/>
		<child link="imu"/>
	</joint>

	<gazebo reference="imu">
    <sensor name="imu_sensor" type="imu">
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <ros>
          <namespace>/imu</namespace>
          <remapping>~/out:=data</remapping>
        </ros>
        <initial_orientation_as_reference>false</initial_orientation_as_reference>
      </plugin>
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
     <imu>
     	<angular_velocity>
     	  <x>
     	    <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>2e-4</stddev>
              <bias_mean>0.0000075</bias_mean>
              <bias_stddev>0.0000008</bias_stddev>
            </noise>
          </z>
        </angular_velocity>
        <linear_acceleration>
          <x>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </x>
          <y>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </y>
          <z>
            <noise type="gaussian">
              <mean>0.0</mean>
              <stddev>1.7e-2</stddev>
              <bias_mean>0.1</bias_mean>
              <bias_stddev>0.001</bias_stddev>
            </noise>
          </z>
        </linear_acceleration>
      </imu>
    </sensor>
  </gazebo>

  <!-- body -->
  <link name="body">
    <visual>
      <origin xyz="0 0 ${-body_height / 2}"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="body_mat"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${-body_height / 2}"/>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>

    <xacro:solid_cuboid_inertial
        width="${body_length}" depth="${body_width}"
        height="${body_height}" mass="${body_mass}">
      <origin xyz="0 0 ${-body_height / 2}"/>
    </xacro:solid_cuboid_inertial>
  </link>
  <gazebo reference="body">
    <material>Gazebo/Grey</material>
  </gazebo>

  <joint name="base_link_to_chasis" type="fixed">
    <parent link="base_link"/>
    <child link="body"/>
  </joint>

  <!-- Wheels -->
  <xacro:wheel lr_prefix="left_bogie" fr_prefix="front"
               lr_pos="${track / 2}"
               fr_pos="${x_center_bogie + wheelbase_bogie / 2}"
               />
  <xacro:wheel lr_prefix="left_bogie" fr_prefix="rear"
               lr_pos="${track / 2}"
               fr_pos="${x_center_bogie - wheelbase_bogie / 2}"
               />
  <xacro:wheel lr_prefix="left_rocker" fr_prefix="rear"
               lr_pos="${track / 2}"
               fr_pos="${x_center_rocker - wheelbase_rocker / 2}"
               />
  <xacro:wheel lr_prefix="right_bogie" fr_prefix="front"
               lr_pos="${- track / 2}"
               fr_pos="${x_center_bogie + wheelbase_bogie / 2}"
               />
  <xacro:wheel lr_prefix="right_bogie" fr_prefix="rear"
               lr_pos="${- track / 2}"
               fr_pos="${x_center_bogie - wheelbase_bogie / 2}"
               />
  <xacro:wheel lr_prefix="right_rocker" fr_prefix="rear"
               lr_pos="${- track / 2}"
               fr_pos="${x_center_rocker - wheelbase_rocker / 2}"
               />

  <gazebo>
    <sensor name="imu" type="imu">
      <always_on>true</always_on>
      <!-- Publish at 30 hz -->
      <update_rate>30</update_rate>
      <plugin name="imu" filename="libgazebo_ros_imu_sensor.so">
        <ros>
          <!-- Will publish to /imu/data -->
          <namespace>/imu</namespace>
          <argument>~/out:=data</argument>
        </ros>
        <frame_name>imu</frame_name>
      </plugin>
    </sensor>
  </gazebo>


  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
  </ros2_control>

</robot>