controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz
    
    arm_controller:
      type: position_controllers/JointGroupPositionController
      
    gripper_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
arm_controller:
  ros__parameters:
    joints:
      - shoulderjoint
      - bicepjoint
      - elbowjoint
      - forearmjoint
      - wristjoint
      - clawjoint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
gripper_controller:
  ros__parameters:
    joints:
      - leftgripperjoint
