controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz
    
    rover_controller:
      type: robot_mechanism_controllers/JointVelocityController
    
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      
    gripper_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rover_controller:
  ros__parameters:
    joints:
      - left_bogie_front_axle
      - left_bogie_rear_axle
      - left_rocker_rear_axle
      - right_bogie_front_axle
      - right_bogie_rear_axle
      - right_rocker_rear_axle
      
    command_interfaces:
      - velocity
      
    state_interfaces:
      - velocity

arm_controller:
  ros__parameters:
    joints:
      - shoulderjoint
      - bicepjoint
      - elbowjoint
      - forearmjoint
      - wristjoint
      - clawjoint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03
        
gripper_controller:
  ros__parameters:
    joints:
      - leftgripperjoint
      - rightgripperjoint
    interface_name: position
