navsat_transform_node:
    ros__parameters:
        # Frequency of the main run loop
        frequency: 30.0

        # Delay time, in seconds, before we calculate the transform from the UTM frame to your world frame.
        delay: 3.0

        # This node assumes that your IMU data is reported in the ENU frame.
        # Transform from NED to ENU !!!!

        magnetic_declination_radians: 0.0

        # Your IMU's yaw, once the magentic_declination_radians value is added to it, should report 0 when facing east. If it
        # doesn't, enter the offset here. Defaults to 0.
        yaw_offset: 0.0

        # If true, the altitude is set to 0 in the output odometry message.
        zero_altitude: false

        # If true, the transform world_frame->utm transform is broadcast for use by other nodes.
        broadcast_utm_transform: false

        # If true, the utm->world_frame transform will be published instead of the world_frame->utm transform. 
        broadcast_utm_transform_as_parent_frame: false

        # If this is true, all received odometry data is converted back to a lat/lon and published as a NavSatFix message as
        # /gps/filtered. Defaults to false.
        publish_filtered_gps: false

        # If this is true, the node ignores the IMU data and gets its heading from the odometry source (typically the
        # /odometry/filtered topic coming from one of robot_localization's state estimation nodes).
        use_odometry_yaw: false

        # If true, will retrieve the datum from the 'datum' parameter below, if available. If no 'datum' parameter exists,
        # navsat_transform_node will wait until the user calls the 'datum' service with the SetDatum service message.
        wait_for_datum: false

        # Instead of using the first GPS location and IMU-based heading for the local-frame origin, users can specify the
        # origin (datum) using this parameter. The fields in the parameter represent latitude and longitude in decimal degrees,
        # and heading in radians. As navsat_transform_node assumes an ENU standard, a 0 heading corresponds to east.
        datum: [55.944904, -3.186693, 0.0]