navsat_transform_node:
    ros__parameters:
        # Frequency of the main run loop
        frequency: 30.0

        # Delay time, in seconds, before we calculate the transform from the UTM frame to your world frame.
        delay: 3.0
        magnetic_declination_radians: 0.0
    
        broadcast_utm_transform: true
        publish_filtered_gps: true
        wait_for_datum: false
        gps_topic: /gps/data
        gps_velocity_topic: /gps/gps_plugin/vel
        imu_data: /imu/data
        odom_frame: odom
        base_link_frame: base_link
        world_frame: map

        