ublox_gps_node_rover:
  ros__parameters:
    debug: 0 # Range 0-4 (0 means no debug statements will print)
    device: /dev/ttyACM0
    frame_id: gps
    uart1:
      baudrate: 9600
      out: 0
      in: 32

    tmode3: 0
    dynamic_model: portable

    fix_mode: auto
    dr_limit: 0
    enable_ppp: false

    rate: 1.0 # in Hz
    nav_rate: 1

    # RTCM out config
    rtcm:
      ids:
        [5, 77, 87, 230, 254] # RTCM Messages to configure for Base station
        # Enabled: GPS MSM7, GLONASS MSM7,
        # GLONASS CP bias, Stationary RTK ref
        # 0xF5 0x05 Stationary RTK reference station
        # ARP
        # 0xF5 0x4A GPS MSM4
        # 0xF5 0x4D GPS MSM7
        # 0xF5 0x54 GLONASS MSM4
        # 0xF5 0x57 GLONASS MSM7
        # 0xF5 0x7C BeiDou MSM4
        # 0xF5 0x7F BeiDou MSM7
        # 0xF5 0xE6 GLONASS code-phase biases
        # 0xF5 0xFE Reference station PVT
        #(u-blox proprietary RTCM Message)
      rates:
        [1, 1, 1, 10, 10] # in number of navigation solutions, must match
        # nav_rate, except for 0xE6

    # GNSS Config
    gnss:
      glonass: true # Supported by zed-f9p
      beidou: false
      qzss: false

    inf:
      all: true # Whether to display all INF messages in console

    # Enable u-blox message publishers
    publish:
      all: true
      aid:
        hui: false

      nav:
        posecef: false
