name: Build CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: src/urc-software
          
      - name: Update Dependencies
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt-get update

      - name: Build
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build
  
  test:
    name: Test
    needs: build
    runs-on: ubuntu-22.04
    container: robojackets/urc-baseimage:humble
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: src/urc-software
          
      - name: Update Dependencies
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          sudo apt-get update

      - name: Colcon Test
        shell: bash
        run: |
          source /opt/ros/humble/setup.bash
          colcon build
          colcon test
